import { DateTime } from "luxon";
import { ResumeRecord } from "./types";

export const RESUME_RECORDS: ResumeRecord[] = [
  {
    type: "EXPERIENCE",
    startDate: "2023-07",
    endDate: null,
    header: "Lead Engineer",
    subheader: "Booz Allen Hamilton",
    location: "McLean, VA",
    technologies: [
      "ProcessUnity",
      "MuleSoft",
      "Git",
      "Jira",
    ],
    points: [
      "Design and develop vendor risk management implementations using ProcessUnity",
      "Work closely with compliance professionals to refine requirements",
      "Coordinate across multiple teams and manage project deliverables in Jira",
      "Create and circulate comprehensive process documentation and demo videos"
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2022-05",
    endDate: "2023-07",
    header: "Sr. Web Developer (Sr. Programmer Analyst)",
    subheader: "University of Dayton",
    location: "Dayton, OH",
    technologies: [
      "Phaser",
      "TypeScript",
      "JavaScript",
      "React",
      "Twig",
      "PHP",
      "MySQL",
      "Git",
      "Jira",
    ],
    points: [
      "Created a browser-based 2-D platformer game for driving student engagement that was played over 60,000 times by more than 5,000 unique students over 12 days.",
      "Wireframed and developed an app used in over 100 course sections that allocates and tracks requests for excused absences and late assignments to reduce the administrative burden on teachers and students.",
      "Developed an app that allows students to send badges to celebrate exceptional performance.",
      "Created an app template for improved styling and code reuse that is used for all new learning apps",
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2018-01",
    endDate: "2022-05",
    header: "Software Engineer",
    subheader: "Cedrus Digital",
    location: "New York City",
    technologies: [
      "TypeScript",
      "JavaScript",
      "Angular",
      "AngularJS",
      "React",
      "Jest",
      "Mocha",
      "Node",
      "Express",
      "Nx",
      "OpenAPI/Swagger",
      "PostgreSQL",
      "Oracle SQL",
      "Azure (Form Recognizer, Cloud Functions, Read API)",
      "Blue Prism",
      "Confluence",
      "Rally",
      "Jira",
    ],
    points: [
      "Developed a full stack application utilizing Azure Cognitive Services and multiple OCR tools.",
      "Developed an enterprise dashboard application that tracks real-time RPA progress and performance.",
      "Developed features on an existing full stack enterprise system for loading healthcare provider data.",
      "Presented bi-weekly client demos and participated in regular technical presentations on design patterns.",
      "Created documentation to assist team members in earning Blue Prism certifications.",
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2017-01",
    endDate: "2017-08",
    header: "Freelance Web Developer",
    subheader: "Self Employed",
    location: "New York City",
    technologies: ["WordPress", "JavaScript", "Git", "GitHub Pages"],
    points: [
      "Designed and developed client websites with WordPress as well as static sites hosted on GitHub Pages.",
      "Documented hosting and backup information with comprehensive turnover papers.",
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2016-11",
    endDate: "2016-12",
    header: "Web Development Intern",
    subheader: "ActiveGiver",
    location: "Bellevue, WA",
    technologies: [" JavaScript", "Ember", "Go", "SQL", "Apiary", "Git"],
    points: [
      "Developed account administrator interface in Ember.",
      "Documented API calls (using Apiary).",
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2014-06",
    endDate: "2016-04",
    header: "Finance Team Manager / Finance Associate",
    subheader: "Vera Institute of Justice - The Guardianship Project",
    location: "New York City",
    points: [
      "Supervised administrative, finance, and operations staff.",
      "Documented finance processes as well as best practices for all departments.",
    ],
  },
  {
    type: "EXPERIENCE",
    startDate: "2013-09",
    endDate: "2014-06",
    header: "Grant Accountant",
    subheader: "Safe Horizon",
    location: "New York City",
    points: [
      "Conducted budget meetings, drafted reports, and performed reconciliations.",
      "Collaborated closely with administrative and direct-service staff from multiple programs.",
    ],
  },
  {
    type: "EDUCATION",
    startDate: "2017-09",
    endDate: "2017-12",
    header: "Software Engineering Immersive",
    subheader: "Fullstack Academy",
    location: "New York City",
    points: [
      "Stackathon People's Choice Award (WDF-1709, for Phoneme Alexa Skill)",
    ],
  },
  {
    type: "EDUCATION",
    startDate: "2009-08",
    endDate: "2012-05",
    header: "Bachelor of Science: Business Administration (Accounting)",
    subheader: "Colorado State University",
    location: "Fort Collins, CO",
    points: ["Top 10% of my class (3.79 GPA)"],
  },
];
